var db = [{'name': 'Eihab Abdel-Rahman',
  'job_title': 'Professor, Assoc Chair Grad Studies',
  'email': 'eihab@uwaterloo.ca',
  'phone': ' 519-888-4567 x37737',
  'location': ' DWE 2510',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/eihab.png',
  'research_interests': ['Ergonomics',
   ' Human Factors & Biomedical',
   ' Modeling & Simulation',
   ' Systems Theory & Optimization',
   ' Modeling',
   ' Simulation And Design Of Mechanical',
   ' Electrical',
   ' Electro-mechanical And Biomechanical Dynamic Systems',
   ' Simulation & Design Of MEMS And NEMS',
   ' Dynamic Phenomena In MEMS',
   ' Biomechanics',
   ' Multi-Body Dynamics And Control',
   ' Nanotechnology',
   ' Connectivity And Internet Of Things',
   ' IoT',
   ' Devices',
   ' Application Domains',
   ' Stakeholders'],
  'biography': 'Eihab Abdel-Rahman is a Systems Design Engineering Associate Professor at the University of Waterloo.\rHis research expertise lies in the area of Micro– and Nano– Electronic Mechanical Systems (MEMS/NEMS). He has collaborated with Professor Ali Nayfeh to develop, an accurate, robust, and numerically efficient approach to the modelling and simulation of MEMS and NEMS.\rProfessor Abdel-Rahman has used the modelling technique to analyze and design a wide array of MEMS sensors and transducers such as Radio Frequency (RF) switches, mirrors, filters, and pumps. He is currently working on new filter designs, control strategies for torsional micromirrors, and improving resonant micro-sensors.\rHe is specifically interested in the continued refinement of the modelling and simulation technique, as well as applying it to the design of novel MEMS and NEMS devices for communications and biomedical applications. The biomedical aspect of his work involves applied research in the use of MEMS to build the associated experimental rigs and to design “smart” prosthetic devices.\rWideband Micro Power Generators are also of interest to Professor Abdel-Rahman. He has developed a new class of vibration-based wideband MPGs in collaboration with 2 other UWaterloo professors. Vibration-based MPGs collect energy only from environmental vibrations that lie in a narrow frequency band. His invention replaces a linear oscillator with a nonlinear oscillator as the energy harvesting element of the MPG. Experimental results show that the bandwidth of the new design improves the harvesting bandwidth of "wideband electromagnetic MPGs" by 200-600%. \rThreshold Mass Sensing is also an area in which Professor Abdel-Rahman holds expertise. He has developed 2 new mass sensing mechanisms that are made of MEMS electrostatic resonators. The sensors detect whether a mass deposited on a sensing platform exceeds a pre-set critical (threshold) value rather than trying to quantify it. The unique feature of these mechanisms is that they eliminate the need for readout electronics. Professor Abdel-Rahman is currently leading efforts to use these mass sensors as platforms to develop vapor/gas and biological sensors'},
 {'name': 'Nasser Lashgarian Azad',
  'job_title': 'Associate Professor',
  'email': 'nlashgar@uwaterloo.ca',
  'phone': ' 519-888-4567 x48797',
  'location': ' E7 6424',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/nlashgar.png',
  'research_interests': ['Automotive Powertrain Control',
   ' Vehicle Dynamics',
   ' Controls',
   ' Model Predictive Control',
   ' Automotive',
   ' Autonomous And Connected Car',
   ' Unmanned Vehicle Systems',
   ' Intelligent Transportation Systems',
   ' Electric And Hybrid Vehicles',
   ' Artificial Intelligence',
   ' Optimization',
   ' Optimal And Nonlinear Control',
   ' '],
  'biography': 'Nasser Lashgarian Azad is an Associate Professor in the Systems Design Engineering department and is also part of the University of Waterloo Centre for Automotive Research (WatCAR), as well as the Waterloo Artificial Intelligence Institute. \r He undertook his postdoctoral studies at the Vehicle Dynamics and Control lab in the University of California, Berkeley. His primary research interests lie in control of connected hybrid and electric vehicles, autonomous cars, and unmanned aerial vehicle quadrotors. He is also interested in applications of Artificial Intelligence for solving various engineering problems. \r His articles in the above-mentioned areas have been published in high-calibre journal venues, including IEEE Intelligent Transportation Systems Transaction, IEEE Transactions on Vehicular Technology, Engineering Applications of Artificial Intelligence (an IFAC journal), Mechatronics, ASME Journal of Dynamic Systems, Measurement, and Control, Applied Soft Computing, Neurocomputing, and Engineering Optimization.'},
 {'name': 'Stephen Birkett',
  'job_title': 'Associate Professor',
  'email': 'sbirkett@uwaterloo.ca',
  'phone': ' 519-888-4567 x33792',
  'location': ' E3 3158',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/sbirkett.png',
  'research_interests': ['Piano Design',
   ' Organology',
   ' Physical Systems',
   ' Animal Growth Modelling',
   ' Environmental Systems',
   ' Computer Simulation Of Systems',
   ' Modeling & Simulation'],
  'biography': 'Stephen Birkett is an Associate Professor in the Department of Systems Design Engineering at the University of Waterloo. \rHis research interests are in piano design, organology, physical systems, animal growth modelling, and environmental systems. \rProfessor Birkett has now completed the bulk of his research in early iron and is in the process of starting to draw wire for pianos. He has been working with high-speed imaging of various fortepiano actions. The P-wire has been thoroughly researched, developed and tested over the past decade by Professor Birkett, and is about to enter commercial production. It is drawn in the proportional Nuremburg sizes and has been reported to have the added advantage of natural corrosion resistance.'},
 {'name': 'Jennifer Boger',
  'job_title': 'Assistant Professor',
  'email': 'jboger@uwaterloo.ca',
  'phone': ' 519-888-4567 x38328',
  'location': ' EC4 2033',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/jboger.png',
  'research_interests': ['Biomedical Engineering',
   ' Assistive Technology',
   ' Rehabilitation Engineering',
   ' Aging',
   ' Ambient Technologies',
   ' Zero-effort Technologies',
   ' Transdisciplinary Working',
   ' Connectivity And Internet Of Things',
   ' IoT',
   ' Devices',
   ' Dependability And Security',
   ' Stakeholders'],
  'biography': 'Dr. Boger’s research focuses on intelligent technologies for enhancing the safety, health, wellbeing, and independence of older adults and people with disabilities. Jennifer employs transdisciplinary collaboration throughout her research to advance theory and create operational technologies that reflect the needs, abilities, and contexts of the people using them. A central theme to her research is the development of ambient zero-effort technologies – technologies that blend into people’s environments and operate with little or no perceived effort. Jennifer is also the Schlegel Chair in Technology for Independent Living at the Research Institute for Aging.'},
 {'name': 'Matthew James Borland',
  'job_title': 'Lecturer',
  'email': 'mjborlan@uwaterloo.ca',
  'phone': ' 519-888-4567 x48330',
  'location': ' E7 6306',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/mjborlan.png',
  'research_interests': '',
  'biography': 'Matt Borland is a Lecturer in the Department of Systems Design Engineering at the University of Waterloo. He has researched musical instrument design and construction during his PhD; taught his students how to build electronic musical interfaces; and co-founded the Waterloo Tape Music Club, a collaborative space for exploring new music. Matt’s work has always spanned across disciplines, with many artistic collaborations and projects over the years. He is currently exploring the interface between digital and analog creative processes in the fields of music and photography.'},
 {'name': 'Catherine Burns',
  'job_title': 'Executive Director, Centre for Bioengineering and Biotechnology',
  'email': 'c4burns@uwaterloo.ca',
  'phone': ' 519-888-4567 x33903',
  'location': ' EC4 2121',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/c4burns.png',
  'research_interests': ['Human Factors Engineering',
   ' Systems Engineering',
   ' Safety',
   ' Ergonomics',
   ' Design Process',
   ' Cognitive Engineering',
   ' Human Error',
   ' Decision Making',
   ' Interface Design And Integration',
   ' Usability Testing And Interactive Technology',
   ' Ecological Interface Design',
   ' Cognitive Work Analysis',
   ' Graphical Interface Design And Visualization'],
  'biography': 'Catherine Burns is a Systems Design Engineering Professor and the Director of the Advanced Interface Design Lab at the University of Waterloo.\rShe conducts research in Ecological Interface Design, cognitive work analysis, and graphical interface design and visualization, which has been applied in military systems, healthcare, power plant control, and oil and gas refining.\rEcological Interface Design (EID) draws design principles from both ecological psychology and engineering. The goal of EID is to present the operator with all the information needed to understand how to achieve plant goals while using a transparent interface. Experimentally, EID is showing great promise as an approach to designing interfaces for systems such as petrochemical plants, power plants and in aviation. This research aims to continue to explore this framework and expand its successful implementation to industrial situations.\rProfessor Burns’ current projects include mobile decision support tools for cardiac nurses, supporting situation awareness in power plant operators, diabetes management tools, and supporting human-to-human and human-to-agent collaboration in uninhibited aerial vehicle environments. Her research is sponsored by the Ontario Ministry of Health and Long Term Care, Bell University Labs, Research in Motion (RIM) and NSERC.\rProfessor Burns is the author of over 100 publications and also recently co-wrote a book on EID. She is the Program Chair for the Cognitive Engineering and Decision Making Technical Group of the Human Factors and Ergonomics Society and an Associate Editor for the International Journal of Human-Computer Studies.'},
 {'name': 'Paul Calamai',
  'job_title': 'Professor',
  'email': 'phcalama@uwaterloo.ca',
  'phone': ' 519-888-4567 x33182',
  'location': ' DWE 2518C',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/phcalama.png',
  'research_interests': ['Bilevel Optimization',
   ' Societal & Environmental Systems',
   ' Nonlinear Optimization',
   ' Operations Research',
   ' Facility Location',
   ' Resource Allocation'],
  'biography': 'Paul Calamai is a Professor in the Department of Systems Design Engineering, as well as a part of the Waterloo Institute for Sustainable Energy at the University of Waterloo. \rHis research interests are centred on issues in resource management. In the past, Professor Calamai’s work concentrated on a class of problems called location-allocation problems. New methodologies, as well as state-of- the-art algorithms, were developed for a large class of these problems. Industrial applications include those involving layouts, data analysis, and facility location-allocation.\rOne long term objective is to provide robust, general purpose tools for handling problems with application in areas of transportation engineering, facility location, network design, and traffic assignment. Another current research activity involves the integration of operations research techniques and Graphical Information Systems. Professor Calamai aims to develop decision support tools for analyzing operational strategies in situations where limited resources must be assigned on a demand basis according to varying criteria.'},
 {'name': 'Scott Campbell',
  'job_title': 'Lecturer, Dir, Ctr-Society Tech & Values',
  'email': 'sm2campb@uwaterloo.ca',
  'phone': ' 519-888-4567 x35635',
  'location': ' E3 3174',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/sm2campb.png',
  'research_interests': ['History Of Computing',
   ' Technological Obsolescence',
   ' Technological Momentum',
   ' History Of Technology In Canada'],
  'biography': 'Scott M. Campbell is a Systems Design Engineering Lecturer and Director of CSTV (Centre for Society, Technology and Values) at the University of Waterloo. \rHis research revolves around the role of technology in Canadian society, specifically the history of computing technology and science in Canada. He is also a co-founder of the University of Waterloo Computer Museum.\rIn 2013, Dr. Campbell published an article about the history of WATFOR, a student-oriented Fortran compiler first created by 4 undergraduates at the University of Waterloo in 1965, followed by many other educational languages and application packages. These publications helped put the University of Waterloo on the map and establish its reputation for innovation.\rAnother recent article of Dr. Campbell’s is “Backwater Calculations for the St. Lawrence Seaway and the First Computer in Canada”, an examination of the role of electronic computing methods in the planning of the St. Lawrence Seaway, published in the Canadian Journal of Civil Engineering. \rHis 2006 doctoral dissertation, “The Premise of Computer Science: Establishing Modern Computing at the University of Toronto (1945-1964)” details the first Canadian attempts to join the world of modern computing in the decades after WWII. It culminates with the first graduate computer science department in Canada at the University of Toronto, and several other undergraduate departments at the University of Alberta, the University of Western Ontario, and the University of Waterloo.\rDr. Campbell has participated in numerous lectures, seminars and refereed conference talks. He also received a Course Internationalization Grant (with Karl Griffiths-Fulton) from the University of Waterloo in 2007.'},
 {'name': 'Shi Cao',
  'job_title': 'Assistant Professor',
  'email': 's34cao@uwaterloo.ca',
  'phone': ' 519-888-4567 x36377',
  'location': ' EC4 2127',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/s34cao.png',
  'research_interests': ['Human Factors And Cognitive Ergonomics',
   ' Human Performance And Mental Workload Modeling',
   ' Human-computer Interaction',
   ' Interface Evaluation And Design',
   ' Smart Home And IoT Applications'],
  'biography': 'Shi Cao is pronounced like SHER TSAO. Dr. Cao’s major research area is human factors engineering. His research projects include human performance and workload modeling, human-machine system reliability, and the applications of virtual and augmented reality. He has developed cognitive models and human performance simulation systems that can be used to model and predict human performance and other human factors constructs in various work domains such as human-computer interaction, driving, and aerospace. These modeling methods and engineering tools have been adopted by researchers from universities and research institutes worldwide. \r Google Scholar Researchgate Linkedin'},
 {'name': 'David A Clausi',
  'job_title': 'Professor, Assoc Dean, Research & Extern',
  'email': 'dclausi@uwaterloo.ca',
  'phone': ' 519-888-4567 x37543,519-888-4567 x32604',
  'location': ' CPH 2376D,EC4 2039',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/dclausi.png',
  'research_interests': ['Remote Sensing',
   ' Sea Ice Monitoring',
   ' Satellite Imagery',
   ' Biomedical Imaging',
   ' Digital Image Processing',
   ' Pattern Recognition',
   ' Signal Processing',
   ' Machine Learning',
   ' Computer Vision',
   ' Operational Artificial Intelligence'],
  'biography': 'David Clausi is a Professor in the Department of Systems Design Engineering at the University of Waterloo.\rHis research interests lie in computer vision, image processing, and pattern recognition with an emphasis on the automated interpretation of satellite imagery. \rProfessor Clausi is a multidisciplinary researcher, publishing refereed journal and conference papers in the diverse fields including remote sensing, computer vision, and algorithm design. His research work has led to successful commercial implementations including the creation and selling of a startup company (CREZ). After successful product deployment and sales, CREZ was purchased by Pointstreak Sports Technologies in 2011.\rAs of result of his teaching and research work, Professor Clausi has received multiple awards including the “Research Excellence and Service to the Research Community” award from the Canadian Image Processing and Pattern Recognition Society (CIPPRS) in 2010. He has also received numerous Outstanding Performance Awards and Distinguished Performance Awards as well as two teaching awards (Sanford Fleming Teaching Excellence Award. University of Calgary Teaching Excellence Award).'},
 {'name': 'Christopher Eliasmith',
  'job_title': 'Professor',
  'email': 'celiasmi@uwaterloo.ca',
  'phone': ' 519-888-4567 x32638,519-888-4567 x42638',
  'location': ' HH 331,E7 6324',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/celiasmi.png',
  'research_interests': ['Ergonomics',
   ' Human Factors & Biomedical',
   ' Modeling & Simulation',
   ' Pattern Analysis',
   ' Machine Intelligence & Robotics',
   ' Signal & Image Processing',
   ' Modeling The Function Of Complex Neural Systems',
   ' Theoretical Neuroscience',
   ' Operational Artificial Intelligence',
   ' Robotics'],
  'biography': 'Chris Eliasmith is a Professor jointly-appointed in the Systems Design Engineering department and the Philosophy department, and is also cross-appointed to Computer Science at the University of Waterloo. He is the Director of the Centre for Theoretical Neuroscience at Waterloo, as well as the Canada Research Chair in Theoretical Neuroscience.   The Centre focuses on mathematical characterizations of a variety neural systems, from individual ion channels to large-scale networks.\r Professor Eliasmith heads the Computational Neuroscience Research Group (CNRG), which is developing a framework for modelling the function of complex neural systems (the Neural Engineering Framework or NEF). The NEF is grounded in the principles of signal processing, control theory, statistical inference, and good engineering design, while providing a rational and robust strategy for simulating and evaluating a variety of biological neural circuit functions.  Members of the group apply the NEF to projects characterizing sensory processing, motor control, and cognitive function.\r Work at the CNRG is divided into applications and theoretical development. Theoretical work includes extending the NEF to be more general (e.g. account for a wider range of single cell dynamics), more biologically plausible (e.g., capture network physiology and topology more precisely),  and more adaptive (e.g., including better adaptive filtering, learning, etc.). The CNRG members are exploring general brain functions to explain not only how neural systems implement complex dynamics (the focus of the NEF), but also what neural systems are designed to do in general – i.e., what the basic functional principles of the brain are.\r Regarding applications, the CNRG is building complex single cell networks to test hypotheses about the functioning of a given neural system as well as artificial intelligence and robotics applications. The simulation results are compared against available neural and behavioural data, and are then used to make novel predictions. CNRG members have constructed models of nonlinear adaptive arm control, working memory, locomotion, decision making, quadcopter control, the basal ganglia (implicated in Parkinsons Disease), rodent navigation, and language use.\r Professor Eliasmith’s research team successfully built the world’s most complex simulation of the human brain – Semantic Pointer Architecture Unified Network (SPAUN).  SPAUN consists of 2.5 million simulated neurons, enabling it to perform 8 tasks such as copy drawing, counting, answering questions and fluid reasoning. It runs on a supercomputer, has a digital eye that is used for visual input and a robotic arm used for drawing its responses. \r Professor Eliasmith is the author of “How to build a brain: A neural architecture for biological cognition” and co-author of “Neural Engineering: Computation, representation and dynamics in neurobiological systems”.'},
 {'name': 'Paul Fieguth',
  'job_title': 'Professor and Department Chair',
  'email': 'pfieguth@uwaterloo.ca',
  'phone': ' 519-888-4970,519-888-4567 x43599',
  'location': ' E5 6119,E7 6338',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/pfieguth.png',
  'research_interests': ['Signal & Image Processing',
   ' Societal & Environmental Systems',
   ' Statistical Modeling',
   ' Multiscale Methods',
   ' Statistical Estimation',
   ' Remote Sensing',
   ' Computer Vision',
   ' Society',
   ' Pattern Analysis',
   ' Machine Intelligence & Robotics',
   ' Random Processes In The Environment'],
  'biography': "Paul Fieguth is a Professor, as well as Chair of the Systems Design Engineering department. He is also the Director of the Vision and Imaging Processing Lab at the University of Waterloo.\rHis main areas of research lie in multiscale statistical modelling and remote sensing. Dr. Fieguth is concentrating on the theory development and understanding of scale recursive estimation algorithms for multi-resolution stochastic processes. Such algorithms use a statistically meaningful strategy to break large estimation problems into smaller pieces, leading to vast improvements in efficiency.\rWhile these algorithms are capable of extremely fast assimilation of data, it is difficult to determine the appropriate multiscale model for a given application of interest. The model assumes a time-invariant model underlying the measurements, and the estimates produced by the model often possess certain multiscale artifacts. Dr. Fieguth aims to address these limitations in the context of a specific data assimilation problem involving a time-varying system: the world's oceans’ surface shape. This approach has allowed him and his research team to contribute to an oceanography issue, while simultaneously providing access to an extensive data set on which to test their algorithms.\rDr. Fieguth’s work in remote sensing is conducted in collaboration with researchers in oceanography who supply physical models, observational data, and the scientific expertise to ensure that meaningful answers are being computed to meaningful problems. Past and ongoing remote sensing efforts include ocean altimetry (production of ocean-surface maps), ocean hydrography (estimation of volumetric temperature fields), acoustic tomography (estimation of large-scale oceanographic features from measurements of sound propagation), and geodesy (determining high-resolution features of the earth's gravitational field from ocean-surface features)."},
 {'name': 'Maud Gorbet',
  'job_title': 'Associate Professor, Director, Biomedical Eng',
  'email': 'mgorbet@uwaterloo.ca',
  'phone': ' 519-888-4567 x30154,519-888-4567 x37009,519-888-4567 x37009,519-888-4567 x38590,519-888-4567 x42602',
  'location': ' E5 6113,OPT 228,OPT 235,CPH 1335C,E7 6444',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/mgorbet.png',
  'research_interests': ['Biocompatibility',
   ' Biomedical Devices',
   ' Biomaterials',
   ' Biological Response To Materials',
   ' Ergonomics',
   ' Human Factors & Biomedical'],
  'biography': 'Maud Gorbet is a Systems Design Engineering Associate Professor and is cross-appointed with the School of Optometry and the Centre for Contact Lens Research at the University of Waterloo. \rHer research focuses on problems of biocompatibility with biomaterials and biomedical devices. While biomedical devices have significantly improved quality of life and increased life expectancy of millions of people, their use is not without complications such as infection, thrombosis and fibrosis. Although the overall rate of complications remains low, the consequences may have fatal outcomes. \rResearch in Professor Gorbet’s lab aims to understand interactions between biomaterials and biological systems. A better understanding of the mechanisms of material-induced cellular activation will enable the design of materials and/or therapeutic strategies that improve biocompatibility and will hence reduce the risks of complications. Some of her research currently focuses on the mechanisms of material-induced thrombosis (blood clot formation) with mechanical heart valves and coronary stents. In-vitro models are being developed to characterize how the blood system (platelets, leukocytes and proteins) interacts with medical-grade metals to create a prothrombotic state. These results will later be used to develop in-silico thrombosis models.\rProfessor Gorbet is also interested in the development of better in-vitro models that can help understand and solve material biocompatibility problems. These in-vitro models are used to identify the interactions between the material and biological systems and test hypotheses regarding the mechanisms of these interactions. These findings can then be verified in-vivo or in clinical settings. Ophthalmic biomaterials, such as soft contact lenses and keratoprosthesis, are currently the main focus of this research.'},
 {'name': 'Glenn Heppler',
  'job_title': 'Professor',
  'email': 'heppler@uwaterloo.ca',
  'phone': ' 519-888-4648',
  'location': ' E3 4109',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/heppler.png',
  'research_interests': ['Dynamics And Control Of Structures',
   ' Structural Dynamics',
   ' Modeling & Simulation',
   ' Flexible Robot Dynamics And Control',
   ' Dynamics Of Multibody And Mechatronic Systems',
   ' Multilink And Single Link Systems'],
  'biography': 'Glenn Heppler is a Professor in the Department of Systems Design Engineering and cross-appointed to the Mechanical and Mechatronics Engineering department at the University of Waterloo.\rProfessor Heppler’s research interests include the dynamics of structures, and multilink and single link systems. He is pursuing several research projects that involve the dynamics and control of a wide range of flexible structures. These structures range from flexible robotic manipulators, to bridges, and to structures with significant gyroscopic elements.\rThe study of structurally flexible robotic arms is also being pursued by Professor Heppler in the context of dynamic mass capture. Dynamic mass capture is the acquisition of a payload by the robot when there is a significant nonzero relative velocity between the robot end effector and the payload. Both the modelling of the dynamics of this class of systems and the control of the system behaviour is being examined in his research. \rAdditionally, Professor Heppler has several publications on subjects such as natural frequencies and large-stroke electrostatic micro-actuators.'},
 {'name': 'Keith Hipel',
  'job_title': 'Professor',
  'email': 'kwhipel@uwaterloo.ca',
  'phone': ' 519-888-4567 x32830',
  'location': ' DWE 2518B',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/kwhipel.png',
  'research_interests': ['Modeling & Simulation',
   ' Societal & Environmental Systems',
   ' Compliance To Environmental Laws And Regulations',
   ' Conflict Resolution',
   ' Environmental Impact Assessment',
   ' Multiple Criteria Decision Making',
   ' Random Processes In The Environment',
   ' Resource Allocation',
   ' Environmental Systems Management',
   ' Time Series Modelling',
   ' Water'],
  'biography': 'Keith Hipel is a Systems Design Engineering Professor at the University of Waterloo, as well as a Professional Engineer in Ontario.\rHe is interested in interdisciplinary research from a Systems Engineering perspective on the development of conflict resolution, multiple criteria decision analysis (MCDA), time series analysis and other methodologies for addressing problems lying at the interface of society, technology and the environment. These methodologies have multiple application purposes such as water resources management, hydrology, environmental engineering, and sustainable development.\rSince 1976, Professor Hipel has taught engineering, mathematics, optimization, workshop, conflict analysis, and time series analysis courses. He is also the co-author of books and software used in the Conflict Analysis and Time Series Modelling courses. Furthermore, he is the Co-Founder and Director of student exchange programs with Tottori and Kyoto Universities, as well as the Tokyo Institute of Technology in Japan. Professor Hipel has presented at multiple seminars in several countries including USA, China, Japan, Israel, France, Germany, Brazil, India, the UK, Singapore and Hong Kong. \rIn addition to his research work, he has received numerous national and international professional engineering awards. On April 27th, 2006, the Senate of École Centrale de Lille, one of France’s highly respected Grand Écoles, voted to award Professor Hipel a Doctor of Engineering Degree (DEng), Honouris Causa, for his exceptional contributions to the development of Systems Engineering methodologies.'},
 {'name': 'Igor Ivkovic',
  'job_title': 'Lecturer',
  'email': 'iivkovic@uwaterloo.ca',
  'phone': ' 519-888-4567 x43500',
  'location': ' E7 6302',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/iivkovic.png',
  'research_interests': ['Information Systems',
   ' Knowledge Engineering',
   ' Software Engineering'],
  'biography': '"Every word or concept, clear as it may seem to be, has only a limited range of applicability." \r— Werner Heisenberg\r I have a proven track record of tackling complex problems with ingenuity, and delivering high-quality results to project stakeholders. I am particularly adept at applying theory to real-world problems, implementing concrete solutions, and following through to ensure project success. \r My practical as well as theoretical focus has been on integration, utilization, and consistency management in complex information systems. The integration concerns distributing information among people, processes, and technology to achieve common understanding. The utilization relates to recognizing matching business contexts and applying the information to support decision making and process control. The consistency management pertains to ensuring equivalency of information during the course of system evolution. And to address the underlying complexity of information systems, I have performed system modeling, process modeling, and data modeling, and have aligned the models with diverse stakeholder concerns.\r I have worked for over a decade tackling complex information systems (IS) and information technologies (IT) problems in a number of industries, such as computer software, media production, web publishing, and higher education. This experience affords me the understanding of vested technical as well as non-technical concerns, and ability to effectively manage the gap between business and technical stakeholder expectations.'},
 {'name': 'Ning Jiang',
  'job_title': 'Assistant Professor',
  'email': 'n34jiang@uwaterloo.ca',
  'phone': ' 519-888-4567 x43677',
  'location': ' E7 6446',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/n34jiang.png',
  'research_interests': ['Biological Signal Processing',
   ' Intelligent Human-machine Interfaces (HMI)',
   ' Advanced Prosthetic Control With Electromyography (EMG)',
   ' Real Time Close-loop Brain Computer Interface For Stroke Rehabilitation',
   ' Electrocardiogram (ECG EKG)',
   ' EHealth',
   ' MHealth',
   ' Robotics'],
  'biography': 'Dr. Jiang’s research leverages signal processing methods and artificial intelligence algorithms for biological signals, such as Electroencephalogram (EEG) and Electromyography (EMG), for neurorehabilitation engineering applications. In particular, his research focuses on new human-machine interfacing (HMI) technologies, including brain-computer interfaces (BCI) and muscle-man-interfaces (MMI). His innovations have resulted in new, more effective upper limb prosthetic control technologies and accelerated rehabilitation of motor functions for patients suffering from disorders, such as stroke. His research has also been applied more broadly, to HMI for applications in kinesiology, neural plasticity (cortical and peripheral), ergonomics and other related areas. These contributions have not only advanced the scientific knowledge of the field but have also achieved direct impacts on the biomedical industry as described below.\rTo date, Dr. Jiang has authored and co-authored 62 refereed journal papers and 62 conference papers (full-length papers and extended abstracts), primarily within the top-most venues for the biomedical engineering, neurorehabilitation, neurophysiology, signal processing, machine intelligence and related disciplines. Nearly half of his journal papers were published in EMBS’ transactions and journals. That these contributions are achieving impact is clear from how often they have been cited (Web of science: 1179, H-index: 20, Google: 2392, H-index 25), and that Dr. Jiang has been invited to present his work at 11 different international conferences, as plenary speaker, workshop speaker, etc. \rSince he started his independent academic career in 2015, Dr. Jiang secured over $1.4 million (CAD) direction research fund in peer-reviewed competitions to support his program (as PI and co-PI). This includes the NSERC Discovery Accelerator Supplement, awarded to only 4% of thousands of applicants in the annual competition. This is a rare feat for a first-time applicant. Dr. Jiang was also recently awarded the highly competitive 2018 Early Researcher Award by the Province of Ontario Ministry of Research, Innovation, and Science. \rDr. Jiang has supervised and co-supervised four post-doctoral fellows, six Ph.D., 21 Master’s, and 14 undergraduate students. Five Ph.D. students under his day-to-day supervision have successfully defended their Ph.D. degrees. The vast majority of these 40+ early stage researchers have moved on to research positions in academia, government or the private sector.\rDr. Jiang’s service to the scientific and engineering community has been extensive, including as an Associate Editor for the IEEE Journal in Biomedical and Health Informatics, Frontiers in Neuroscience, and the Brain-Computer Interfaces. He also Co-Chaired the Neurorehabilitation and Prosthetics Symposium at the IEEE International Neural Engineering Conference (2017), was Track Chair of the Myoelectric Control Symposium (2017), was Associate Editor for the IEEE International Conference of Robotics and Automation (2016), and will Co-Chair the upcoming workshop on BCI in aging research at the IEEE International Conference on Systems, Man and Cybernetics (2018). He was elevated to Senior Member of IEEE/EMBS in 2014.'},
 {'name': 'Jonathan Kofman',
  'job_title': 'Associate Professor',
  'email': 'jkofman@uwaterloo.ca',
  'phone': ' 519-888-4567 x45185',
  'location': ' E7 6318',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/jkofman.png',
  'research_interests': ['3D Imaging',
   ' 3D Vision',
   ' Surface Measurement',
   ' Optical Sensor Design',
   ' Vision/inspection',
   ' Biomedical Sensors/systems',
   ' Intelligent Assistive Devices',
   ' Wearable Robotics',
   ' Prosthetics',
   ' Orthotics',
   ' Machine Intelligence & Robotics',
   ' Human-machine Interfaces',
   ' Human-robot Interaction',
   ' Pattern Analysis',
   ' Computer Vision',
   ' Signal & Image Processing',
   ' Biomechatronics',
   ' Robotics',
   ' Operational Artificial Intelligence'],
  'biography': "Jonathan Kofman is a Professor in the Department of Systems Design Engineering and cross-appointed to the Department of Mechanical and Mechatronics Engineering at the University of Waterloo.\rProfessor Kofman's research focuses on biomechanics and biomedical device/system design; 3D computer vision and 3D-vision sensor-design; and human-robot interfaces and human-robot interaction. His earlier research has resulted in commercial laser-camera range-sensors and worldwide used CAD/CAM systems in prosthetics. In addition, three patents were recently issued for: unconstrained range-sensing for application in a hand-held 3D scanner and 3D robot-vision scanner; an articulating joint for human-assistive devices and robotic applications; and full-field optical/vision-based 3D surface shape measurement.\rProfessor Kofman’s research lab, Intelligent Human Machine Systems Lab/ Optomechatronic Systems Laboratories, has done work in human-assistive orthotic-system design and biomechatronic systems in collaboration with Dr. Edward Lemaire of the Ottawa Hospital Rehabilitation Centre. Their research has led to new designs of a Stance-Control Knee-Ankle-Foot Orthosis (SCKAFO). The SCKAFO is a leg brace that first locks the knee joint when the leg is weight bearing (to support the weight of the body). It then unlocks the knee when the leg is unloaded, to permit the knee to flex, in order to allow the leg to swing forward smoothly with the foot clearing the ground while taking the next step. Ongoing research includes clinical testing of the new orthoses, design of new wearable human-assistive robotic/orthotic systems, and development of measurement and analysis systems for assessing dynamic stability in human walking. One patent has been issued and another one is pending related to this biomedical research.\rProfessor Kofman has been co-recipient and co-author of several research paper/research awards, and was awarded the En-Hui Yang Engineering Research Innovation Award from the UWaterloo Faculty of Engineering in 2008."},
 {'name': 'Carolyn MacGregor',
  'job_title': 'Associate Professor & Associate Chair Undergraduate Studies',
  'email': 'cgmacgre@uwaterloo.ca',
  'phone': ' 519-888-4567 x35566,519-888-4567 x32897',
  'location': ' E5 6128,EC4 2129',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/cgmacgre.png',
  'research_interests': ['Individual Differences',
   ' Information Manipulation',
   ' Usability Testing',
   ' Human-computer Interaction',
   ' Driver Performance And Safety',
   ' Cognitive Ergonomics',
   ' Road Safety',
   ' Virtual Environments',
   ' Ergonomics',
   ' Human Factors & Biomedical'],
  'biography': 'Carolyn MacGregor is an Associate Professor in the Department of Systems Design Engineering at the University of Waterloo. She is also an Associate Chair for Undergraduate Studies with the Centre for the Advancement of Co-operative Education. \rDr. MacGregor\'s research applies her engineering and psychology degrees to the study of human factors, product design, and virtual environments. Her primary research interests are in the navigation and manipulation of virtual environments and 3D simulations, usability testing and human-computer interactions, and pedestrian and driver safety.\rHer current projects include the development of virtual trailblazing techniques for human navigation, as well as the development of the "veball”, a 3D input device with haptic feedback for manipulating virtual objects in 3D applications. Dr. MacGregor has been actively involved in human factors research and consulting activities since 1980.\rHer main areas of teaching focus on human factors engineering, user-centred design, and cognitive ergonomics. As a discipline, human factors engineering is a combination of engineering, psychology, kinesiology and anthropology. The field of cognitive ergonomics strives to understand how humans process and manipulate information so that their limitations and capabilities can be taken into account when designing effective tasks, interfaces, and systems.'},
 {'name': 'Nima Maftoon',
  'job_title': 'Assistant Professor',
  'email': 'nmaftoon@uwaterloo.ca',
  'phone': ' 519-888-4567 x47654',
  'location': ' E7 6426',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/nmaftoon.png',
  'research_interests': ['Hearing Science',
   ' Auditory Mechanics',
   ' Medical Devices',
   ' Hearing Implants',
   ' Diganostic Tools',
   ' Biomechanics',
   ' Vibration',
   ' Acoustics',
   ' Otolaryngology',
   ' Computational Fluid And Solid Mechanics',
   ' Physiological Measurements And Modelling',
   ' Cancer Mechanics',
   ' Metastasis',
   ' Computational Oncology'],
  'biography': 'Hearing Lab\rThe long-term research goal of the Hearing Lab is to develop advanced devices and methods for diagnosis and treatment of hearing loss and other auditory pathologies. Such work requires discoveries about the processes involved in hearing as well as developing innovative engineering solutions. To serve these requirements, we use and advance knowledge in fields such as biomechanics, solid and fluid mechanics, acoustics, system identification and hearing physiology. The research portfolio of the Hearing Lab includes device development, advanced acoustic and vibration measurements and analysis in animal and human ears supplemented with analytical and computational modelling.\r Computational Metastasis Lab\rComputational Metastasis Lab is focused on developing predictive tools that enable personalized cancer treatments. The lab uses advanced computational mechanics algorithms in conjunction with clinical image processing in creation of the predictive tools. We measure data in vitro and in vivo in human and animals to validate our mathematical models of tumor-cell circulation, intravasation and extravasation using advanced optical methods and using clinical modalities.\r Available Positions\rWe are looking for graduate students with strong background in microfabrication, image processing or CFD, computational solid mechanics and fluid-structure interaction. Following experience and knowledge are highly favourable: lattice-Boltzmann method, finite-element method, 3-D model reconstruction using serial images, image processing algorithms, Fortran, C and Python programming. \rCanadian and permanent resident students and students with funding are strongly encouraged to apply. \rIf interested, please send me an email summarizing your education, background and interests along with your CV and transcripts.'},
 {'name': 'John McPhee',
  'job_title': 'Professor',
  'email': 'mcphee@uwaterloo.ca',
  'phone': ' 519-888-4567 x35341',
  'location': ' E3 4114',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/mcphee.png',
  'research_interests': ['Modelling And Simulation',
   ' Multibody Dynamics',
   ' Biomechanics',
   ' Vehicle System Dynamics',
   ' Mechatronics',
   ' Mechanism And Machine Design',
   ' Computational Methods For Dynamic Analysis',
   ' Sports Engineering',
   ' Design Optimization',
   ' Systems Theory',
   ' Autonomous And Connected Car',
   ' Automotive',
   ' Hybrid Electric Vehicles',
   ' Applications In Robotics And Mechatronic Systems',
   ' Advanced Manufacturing',
   ' Robotics'],
  'biography': 'John McPhee received his degrees in Mechanical Engineering from Acadia University, the Technical University of Nova Scotia, and the University of Waterloo, Canada. He worked at the Université de Liège, Belgium, and Queen’s University, Canada, before taking a faculty position in 1992 at Waterloo, where he is now a Professor in Systems Design Engineering and the Canada Research Chair in Biomechatronic System Dynamics. \r Dr. McPhee is Canada’s foremost researcher in the field of multibody system dynamics, with principal application to the analysis and design of vehicles, mechatronic devices, biomechanical systems, and sports equipment. He pioneered the use of linear graph theory to model multi-domain dynamic systems, and his research algorithms have been commercialized by Maplesoft and are a core part of the MapleSim engineering package, which is used by thousands of engineers and researchers at Toyota, NASA, Ford, Honda Motorcycle, General Motors, Harley Davidson, TRW, and others. Dr. McPhee has won several research awards, including the I.W. Smith Award, the Premier’s Research Excellence Award, and Best Paper Awards from the American and Canadian Societies for Mechanical Engineering and the International Society for Terrain-Vehicle Systems. He has also received awards for his teaching, written over 200 peer-reviewed papers, consulted to many industries in Canada and the United States, and appeared as an expert witness in the Federal Court of Canada. He has supervised 70 graduate students and postdoctoral fellows, and is a registered Professional Engineer in the Province of Ontario. \r Dr. McPhee has served as the Associate Editor for seven international journals, two of which he helped to found – Multibody System Dynamics and the ASME Journal for Computational and Nonlinear Dynamics – which are the two flagship journals in this field. He has given invited keynote presentations around the globe, delivered webinars on automotive system modelling to thousands of practicing engineers, and in 2005 he was elected a Fellow of the American Society of Mechanical Engineers. \r Dr. McPhee was a co-founder of the Waterloo Centre for Automotive Research (WatCAR) and, during his 2007-2009 tenure as the Executive Director, he grew WatCAR from a fledgling research centre to the largest academic cluster for automotive engineering research in Canada, garnering international recognition and over $10 million in annual funding. Following this tenure, he was the first academic to spend a sabbatical year at the Toyota Technical Center in Ann Arbor, Michigan, where he launched his NSERC/Toyota/Maplesoft Industrial Research Chair in Mathematics-Based Modelling and Design. He is a Fellow of the Canadian Academy of Engineering and the Canadian Society of Mechanical Engineers. \r In 2014, Dr. McPhee received the prestigious NSERC Synergy Award from the Governor-General of Canada.'},
 {'name': 'Nima Khademmohtaram',
  'job_title': 'Lecturer',
  'email': 'nkhademm@uwaterloo.ca',
  'phone': ' 519-888-4567 x46898',
  'location': ' E7 6304',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/nkhademm.png',
  'research_interests': ['Biomaterials',
   ' Tissue Engineering',
   ' Stem Cells',
   ' Biomedical Devices '],
  'biography': ''},
 {'name': 'Kumaraswamy Ponnambalam',
  'job_title': 'Professor',
  'email': 'ponnu@uwaterloo.ca',
  'phone': ' 519-888-4567 x43282',
  'location': ' E7 6316',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/ponnu.png',
  'research_interests': ['Design Optimization Under Uncertainty',
   ' StoHigh-level Design Of Software Structures',
   ' Systems Theory & Optimization',
   ' Software Engineering',
   ' Sustainable Development',
   ' Large Scale Optimization',
   ' Reliability Based Design Of Large Systems',
   ' Sustainable Product Design',
   ' Societal & Environmental Systems',
   ' Modeling & Simulation',
   ' Application Of Intelligent Systems',
   ' Water'],
  'biography': 'Kumaraswamy Ponnambalam is a Professor in the Department of Systems Design Engineering at the University of Waterloo. \rHe has previously worked at several academic institutions including the College of Engineering in Madras, India; the University of Toronto, the University of Ottawa and the Technical University of Delft in the Netherlands. In the past, Professor Ponnambalam has been a Research Assistant Professor and the Associate Chair of Graduate Studies in the Systems Design Engineering department at UWaterloo.\rHis research interests include design optimization under uncertainty, mainly pertaining to issues in civil, chemical, electrical and environmental engineering. Due to the interdisciplinary nature of the many applications, much of the work has been done in collaboration with colleagues from both within and outside the university. In addition, Professor Ponnambalam is also working in the Application of Intelligent Systems to hydrology and water resources, health decision making, control of satellite communications, and fault detection analysis.\rHe has received research funding from the Communitech Database Grant, the FEDDEV Grant, NSERC Engage Grant, NSERC Discovery Grant, Ontario Research Fund, MITACS Doctoral Scholarship, and CITO Industrial Research Grant. As a result of his research work, Professor Ponnambalam has received numerous awards including the “Distinguished Performance in Research, Teaching, and Service, Faculty of Engineering Award”, from the University of Waterloo in 2006; and the “Best Student Paper Award” at the 2011 International Conference of Financial Engineering.'},
 {'name': 'Parsin Haji Reza',
  'job_title': 'Assistant Professor',
  'email': 'phajirez@uwaterloo.ca',
  'phone': ' 519-888-4567 x40172, \u200b+1-519-888-4567 EXT 40172',
  'location': ' E7 6416',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/phajirez.png',
  'research_interests': ['Photoacoustic Remote Sensing (PARS) Microscopy',
   ' Multi-scale Functional And Molecular Photoacoustic Imaging',
   ' Non-contact Detection Of Photoacoustic Signals',
   ' All Optical Nano-structured Detectors For Photoacoustic Tomography',
   ' Photoacoustic Wavefront Shaping',
   ' Optical Coherence Tomography (OCT)',
   ' Multi-photon Microscopy',
   ' Novel Multi-modality Optical Imaging Techniques',
   ' Design And Fabrication Of Micro-endoscopy Systems',
   ' Super-resolution Imaging Techniques',
   ' Real-time And 3D Biomedical Imaging',
   ' Dual-Modality Photoacoustic And Ultrasound Imaging Systems',
   ' Novel Optical And Fiber-based Components',
   ' Novel Laser Systems For Biomedical Applications',
   ' Optical Sensors'],
  'biography': "Dr. Haji Reza joined the University of Waterloo in April 2018 as an Assistant Professor in the Department of Systems Design Engineering, after completing his doctoral and postdoctoral research at the University of Alberta and completing an undergraduate degree in optical engineering. As a graduate student, Dr. Haji Reza has published 21 papers in high impact, peer-reviewed journals (14 first-author including Nature's light science and applications and Optica), two book chapters about optical systems and holds five patents. Also, he has contributed to 35 abstracts and conference proceedings related to optics and biomedical optics. Dr. Haji Reza has received various national and international scholarships as well as academic and industrial awards and recognition, including the Izaak Walton Killam Memorial Scholarship, Alberta Innovates-Technology Futures, Dissertation Fellowship, Andrew Stewart Memorial Prize and SPIE Startup challenge and scholarships for his innovative research work.\r Dr. Haji Reza pioneered Photoacoustic Remote Sensing (PARS) microscopy, a novel absorption-based, non-contact, non-invasive, label-free imaging technique. In November 2014, he co-founded a start-up company illumiSonics inc., holding the position of CEO from November 2014 to March 2018. illumiSonics is currently focused on commercializing PARS technology for pre-clinical and pharmaceutical applications. During Dr. Haji Reza's leadership role at illumiSonics, he raised private investments and attracted notable individuals and international companies. He is currently the Chairman of the Board of illumiSonics, overseeing the major policies and decisions of this Company."},
 {'name': 'Reem Roufail',
  'job_title': 'Lecturer',
  'email': 'rroufail@uwaterloo.ca',
  'phone': ' 519-888-4567 x46892',
  'location': ' E7 6312',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/rroufail.png',
  'research_interests': ['Precious Metal And Material Reclamation.',
   ' Material Selection/substitution For Design.',
   ' Advanced Manufacturing.',
   ' Smart Material (memory Alloys And Polymers).',
   ' Design For Energy Efficiency (heavy Industry As Comminution In Mining).',
   ' Renewable Energy.'],
  'biography': ''},
 {'name': 'Siby Samuel',
  'job_title': 'Assistant Professor',
  'email': 's5samuel@uwaterloo.ca',
  'phone': ' 519-888-4567 x37656',
  'location': ' EC4 2119',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/s5samuel.png',
  'research_interests': ['Simulation & Virtual Reality/Augmented Reality',
   ' Novice And Older Driver Training',
   ' Predictive & Conceptual Modeling Of Behavior',
   ' Eye Tracking',
   ' Attention & Cognition',
   ' Perception',
   ' Decision Making',
   ' Aging',
   ' Automotive Human Factors',
   ' Autonomous Vehicles And Connected Vehicles & Intelligent Transportation Systems',
   ' Caregiver Behaviors & Errors',
   ' Assistive & Automotive Interfaces',
   ' Vulnerable Road User Safety (Pedestrians & Bicyclists)',
   ' Motorcyclist Safety',
   ' Special Populations (ADHD & Dementia)',
   ' Traffic Control Devices & Roadway Infrastructure Design'],
  'biography': 'Dr. Samuel’s research broadly spans surface transportation human factors, healthcare human factors and safety. Dr. Samuel utilizes a variety of experimental techniques to measure human performance and study human behavior. The core theme of his work is centered around the etiology of crashes (or errors) or the study of crash (error) causation. The goal is to advance user safety by accounting for the limitations of both,  infrastructure and interface device design. Specifically, Siby’s research deals with:\r- Road User (drivers, pedestrians, bicyclists and motorcyclists) safety\r- Caregiver Behavior and Medical Errors\r- Autonomous vehicles, Connected vehicles and Intelligent Transportation Systems (ITS)\r- Design and assessment of Traffic Control Devices, Roadway Infrastructure and Automotive Interfaces\r- Application of Virtual Environments for Rehabilitation and Occupational Therapy.\r- Development and evaluation of population-specific, cognitive Training Interventions (novice drivers, older drivers aged 65 and above, pedestrians, special population with ADHD and mild cognitive impairments)\r- Measurement of Driver Distraction, Fatigue, Mental Workload and Situation Awareness.'},
 {'name': 'Gordon Savage',
  'job_title': 'Professor',
  'email': 'gjsavage@uwaterloo.ca',
  'phone': ' 519-888-4567 x33941',
  'location': ' DWE 2518D',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/gjsavage.png',
  'research_interests': ['Modeling & Simulation',
   ' Reliability And Quality In Design',
   ' Systems Theory & Optimization',
   ' Discrete Continuum Theories',
   ' Mechatronics Design',
   ' Large Systems Modelling Through Subsystems',
   ' Modelling And Optimization Of Systems',
   ' Pattern Analysis',
   ' Machine Intelligence & Robotics'],
  'biography': 'Gordon Savage is a Systems Design Engineering Professor at the University of Waterloo.\rHe is interested in the application of systems theory to field and continuum problems. Professor Savage’s research aims to produce general models of spatially continuous processes such as heat conduction, diffusion, and elasticity. These models provide conceptual or computational advantages, which unify or categorize existing numerical methods such as finite elements and finite differences.\rProfessor Savage’s research focuses on the areas of non-linear media modelling, coupled fields, probabilistic boundary conditions and constitutive properties; flexibility and impedance finite elements; and grid optimization methods.\rAnother area of his research is reliability and quality of design, which is in response to the increasing importance of safety and quality objectives as more complex systems are being designed and environmental standards are becoming stricter. The concepts of reliability and quality have proven to be useful in helping quantify constraints and selective alternative designs.\rProfessor Savage’s research aims to provide a unified methodology for the design of various physical systems that encompass both quality and safety design criteria. The methodology is applicable to multi-disciplinary systems and incorporates several mathematical theories of probability assessment. The research results should provide a design methodology well suited, but not restricted to, the design of systems with active redundancy and dependent component failures. Additionally, it should provide important measures that can be used for the comparison and improvement of designs.'},
 {'name': 'Katharine Scott',
  'job_title': 'Assistant Professor',
  'email': 'ka3scott@uwaterloo.ca',
  'phone': ' 519-888-4567 x32811',
  'location': ' EC4 2037',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/ka3scott.png',
  'research_interests': ['Assimilation Of Remote Sensing Data To Improve Our Knowledge Of The State Of Sea Ice In The Arctic',
   ' The Assimilation Of Sea Ice Thickness And/or Sea Ice Temperature From Visual/infrared Sensors.',
   ' The Information Content Of Passive Microwave And Visual Infrared Sensors As It Pertains To Sea Ice Concentration And Thickness',
   ' The Assimilation Of SAR (Synthetic Aperture Radar) Data',
   ' Using Data Assimilation To Estimate Parameters In Turbulence Models',
   ' The Development Of Scale Aware/scale Adaptive Parameterizations',
   ' Water'],
  'biography': 'Andrea Scott is an Assistant Professor in the Systems Design Engineering department at the University of Waterloo.\rHer research focuses on data to improve model predictions. One of Professor Scott’s projects involve the assimilation of remote sensing data to improve knowledge of the state of sea ice in the Arctic. More specifically, she conducts research on the assimilation of sea ice thickness and/or sea ice temperatures from visual/infrared sensors, and uses Synthetic Aperture Radar (SAR) data to estimate sea ice concentration. Other projects of Professor Scott’s include the use of data assimilation to estimate parameters in turbulence models and the development of scale aware/scale adaptive parameterizations.\rBefore working as a professor at UWaterloo, Professor Scott was a postdoctoral researcher at Environment Canada, where she was part of a team working on the assimilation of data to improve forecasts of sea ice conditions.'},
 {'name': 'Mohammad Shafiee',
  'job_title': '',
  'email': 'mjshafie@uwaterloo.ca',
  'phone': '',
  'location': '',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/mjshafie.png',
  'research_interests': ['Artificial Intelligence',
   ' Machine Learning',
   ' Computer Vision '],
  'biography': ''},
 {'name': 'Cameron Shelley',
  'job_title': 'Lecturer',
  'email': 'cshelley@uwaterloo.ca',
  'phone': ' 519-888-4567 x38289',
  'location': ' E3 3173',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/cshelley.png',
  'research_interests': ['Social Determinants Of Technology',
   ' Social Impacts Of Technology',
   ' Philosophy Of Design',
   ' Explanatory Reasoning',
   ' Cognitive Irony'],
  'biography': 'Cameron Shelley is a Lecturer in the Department of Systems Design Engineering at the University of Waterloo. He has held Doctoral and Postdoctoral Fellowships with the Social Sciences and Humanities Research Council of Canada and has previously been a Visiting Scholar at the Philosophy Department at the University of Michigan, Ann Arbor.\rDr. Shelley’s research interests include the philosophy of design, social impact of technology, explanatory and analogical reasoning, and cognitive irony. He has taught a variety of courses including Cities, Technology & Society, Design & Society, Biotechnology & Society, Information Technology & Society, among others.\rIn addition to his research work, Dr. Shelley has received multiple awards such as the UWaterloo Alumni Association Gold Medal for best Ph.D. dissertation. He has also published various articles that include “Biomorphism and models in design” in Philosophy and Cognitive Science II, “Models and ideology in design” in Model-based reasoning in Science and Technology, “Fairness in technological design” in Science and Engineering Ethics, “Why test animals to treat humans?  On the validity of animal models” in Studies in History and Philosophy of Science Part C, and “Hypocrisy as irony” in Metaphor and Symbol.  Additionally, Dr. Shelley published a book entitled “Multiple analogies in science and philosophy” with John Benjamins and edited the “Springer Handbook of Model-based Science, Part I: Models in Engineering, Architecture, and Economical & Human Sciences” with Springer.'},
 {'name': 'Daniel Stashuk',
  'job_title': 'Professor',
  'email': 'stashuk@uwaterloo.ca',
  'phone': ' 519-888-4567 x32982',
  'location': ' EC4 2023',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/stashuk.png',
  'research_interests': ['Ergonomics',
   ' Human Factors & Biomedical',
   ' Modeling & Simulation',
   ' Signal & Image Processing',
   ' Decisions Under Uncertainty',
   ' EMG Signal Simulation',
   ' Machine Intelligence And Knowledge Based Systems',
   ' Adaptive And Nonlinear Systems',
   ' Pattern Analysis',
   ' Quantitative Clinical Diagnosis',
   ' Biosignal Detection And Analysis Electromyographic (EMG) Signal Detection And Analysis',
   ' Clinical Quantitative EMG',
   ' Electrophysiological Characterization Of Neuromuscular Disorders',
   ' Clinical Decision Support',
   ' Motor Unit Number Estimation',
   ' Decomposition-based Quantitative Electromyography '],
  'biography': 'Daniel Stashuk is a Professor in the Department of Systems Design Engineering at the University of Waterloo. \rHis research interests lie in the electrophysiological characterization of neuromuscular disorders, quantitative EMG, EMG signal decomposition, , Decomposition-based Quantitative Electromyography (DQEMG) and EMG signal simulation.\rCurrently, the major objectives of Professor Stashuk’s ongoing research are to develop and evaluate clinical methods that can assist with the characterization of neuromuscular disorders based  on the interpretation of DQEMG results, and to introduce new quantitative statistics that effectively reflect neuromuscular structure and physiology. In addition to his research work, Professor Stashuk has several publications that cover the topics of electromyography and electromyographic signals.'},
 {'name': 'Hamid Tizhoosh',
  'job_title': 'Professor',
  'email': 'tizhoosh@uwaterloo.ca',
  'phone': ' 519-888-4567 x36751,519-888-4567 x46751',
  'location': ' EC4 2011,E7 6314',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/tizhoosh.png',
  'research_interests': ['Artificial Intelligence',
   ' Computer Vision',
   ' Medical Imaging'],
  'biography': 'Dr. Hamid R. Tizhoosh is a Professor in the Faculty of Engineering at University of Waterloo since 2001 where he leads the KIMIA Lab (Laboratory for Knowledge Inference in Medical Image Analysis). Before he joined the University of Waterloo, he was a research associate at the Knowledge and Intelligence Systems Laboratory at the University of Toronto where he worked on dynamic bandwidth allocation using AI methods such as reinforcement learning. His research activities encompass artificial intelligence, computer vision, and medical imaging. He has developed algorithms for medical image filtering, segmentation, and search. As well, he has introduced the "Opposition-based Learning". Dr. Tizhoosh has received support, worth more than $6.0 M, since 2001 for his research and commercialization activities through NSERC, OCE, FedDev, MITACS, MaRS, HTX, IRAP, ORF-RE and industry partners. He is the author of two books, 14 book chapters, and more than 140 journal and conference papers. He has also filed 5 patents in collaboration with WatCo (Waterloo Commercialization Office). Dr. Tizhoosh’s publications have received many citations. He has extensive industrial experience and has worked with numerous companies such as Management of Intelligent Technologies GmbH (Aachen, Germany), Image Processing Systems Inc. (a Markham-based company acquired by Photon Dynamics Inc. (San Jose, CA)), and Medipattern Corporation (Toronto). Presently, he is the AI Advisor of Huron Digital Pathology, St. Jacobs, ON, Canada. Additionally, Dr. Tizhoosh has more than 10 years of experience in commercialization and start-ups. In 2007, he started Segasist Technologies, a start-up that developed image segmentation software for radiation oncology. The company raised more than $2M under his leadership, both as CEO and CTO. He also planned and successfully managed an FDA 510k submission for computer-aided detection for prostate cancer with the help of Sunnybrook Hospital and the London Regional Cancer Centre.'},
 {'name': 'Bryan Patrick Tripp',
  'job_title': 'Associate Professor',
  'email': 'bptripp@uwaterloo.ca',
  'phone': ' 519-888-4567 x41382',
  'location': ' E7 6326',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/bptripp.png',
  'research_interests': ['Computational Neuroscience',
   ' Deep Learning',
   ' Advanced Robotics',
   ' Operational Artificial Intelligence'],
  'biography': 'Bryan Tripp is an Assistant Professor with the Department of Systems Design Engineering and the Centre for Theoretical Neuroscience at the University of Waterloo.\rHe is interested in understanding how the brain processes information. Professor Tripp is currently studying the visual and motor systems of primates. About half the human brain is dedicated to seeing and moving. We have constant experience with these things, but we only vaguely understand how they work. Professor Tripp believes that to understand these things clearly, we must build computational systems that see and move like humans.\rProfessor Tripp aims to develop a realistic large-scale model of the visual-motor networks of the primate brain. Biological vision and motor systems outperform artificial systems in many ways, so a better understanding of these systems may lead to technological advances.'},
 {'name': 'Thomas Willett',
  'job_title': 'Assistant Professor',
  'email': 'twillett@uwaterloo.ca',
  'phone': ' 519-888-4567 x48405',
  'location': ' E7 6438',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/twillett.png',
  'research_interests': ['Mechanics Of Biomaterials And Tissues',
   ' Bone Quality And Fragility',
   ' Engineering Of Bone Mimetic Materials For Skeletal Reconstruction',
   ' Additive Manufacturing'],
  'biography': ''},
 {'name': 'Alexander Wong',
  'job_title': 'Associate Professor',
  'email': 'a28wong@uwaterloo.ca',
  'phone': ' 519-888-4567 x31299',
  'location': ' EC4 2019',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/a28wong.png',
  'research_interests': ['Artificial Intelligence',
   ' Image Processing And Data Analytics',
   ' Medical Imaging',
   ' Scanning',
   ' Sensors And Devices',
   ' Drinking Water',
   ' Autonomous And Connected Car',
   ' Automotive',
   ' Operational Artificial Intelligence',
   ' Robotics',
   ' Smart Infrastructure'],
  'biography': 'Alexander Wong is an Assistant Professor in the Systems Design Engineering department and Co-Director of the Vision and Image Processing (VIP) Research Group at the University of Waterloo. He is also the Canada Research Chair in Medical Imaging Systems. \r His research interests revolve around imaging, image processing, computer vision, pattern recognition, and cognitive radio networks, with a focus on the hardware-software design of integrative medical imaging systems, and biomedical and remote sensing image processing and analysis. He is also interested in multimedia management systems and 3D graphics and game development.\r One of Professor Wong’s key research interests is medical image processing and analysis with applications to prostate, breast, lung and dermatological cancer analysis. He is developing an improved Magnetic Resonance Imaging (MRI) system that recognizes cancer indicators such as tissue characteristics, size and shape. This will allow for enhancements to early stage cancer detection and the capturing of data in a more efficient manner.\r He has published refereed journal and conference papers, as well as patents, in various fields such as imaging, computer vision, graphics, image processing, multimedia systems, and wireless communications. Professor Wong is the co-author of the textbook “Data Structures and Algorithms in a Nutshell’ and has also co-authored the chapter “Melanoma decision support using lighting-corrected intuitive feature models” in Computer Vision Techniques for the Diagnosis of Skin Cancer. Additionally, he co-wrote the chapter “Nonparametric sample-based methods for image understanding” in Emerging Topics in Computer Vision.\r As a result of his research work, Professor Wong has received multiple awards such as the Early Research Award from the Ministry of Economic Development and Innovation, as well as the Alumni Gold Medal from the University of Waterloo in 2012.  In 2009 and 2014, he received Best Paper Awards from the Canadian Image Processing and Pattern Recognition Society (CIPPRS).  He also received  two Outstanding Performance Awards, an Engineering Research Excellence Award, as well as a Distinguished Paper Award by the Society of Information Display (2015).   \rProfessor Wong holds 3 patents and 10 patent applications in the area of imaging.'},
 {'name': 'Tze Wei Yeow',
  'job_title': 'Professor',
  'email': 'jyeow@uwaterloo.ca',
  'phone': ' 519-888-4567 x32152',
  'location': ' E3 3159',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/jyeow.png',
  'research_interests': ['Ergonomics',
   ' Human Factors & Biomedical',
   ' MEMS/NEMS',
   ' Optomechatronic Systems',
   ' Biomedical Sensors',
   ' Lab-on-a-chip',
   ' BioMEMS',
   ' Microassembly',
   ' Microelectromechanical Systems',
   ' Robot Mechantronic Design',
   ' Microsystem',
   ' Advanced Manufacturing',
   ' Nanotechnology'],
  'biography': 'John Yeow is a Professor in the Department of Systems Design Engineering and is cross-appointed to Mechanical and Mechatronics Engineering and Electrical and Computer Engineering at the University of Waterloo. He is also the Director of the Advanced Micro & Nanodevice Lab at the university and holds the Canada Research Chair in Micro and Nanodevices.\rProfessor Yeow’s research expertise lies in Micro-/Nano- Electro Mechanical systems. He aims to develop mechanical machines that are integrated with microelectronics at the micron scale. New device concepts include, but are not limited to: the integration of micro-optics components, miniature signal processing devices, biomedical/genome processing devices, miniature electromechanical wireless components (filters, mixers, antennas), miniature opto-electromechanical devices (optical cross connect, optical relays, optical multiplexers, deformable optics), miniature biosensors and environmental sensors, and microfluidics devices. Professor Yeow also explores issues such as self-testing, self-assembly, and automated packaging.\rHe is currently developing nanodevices and highly selective sensors that will help create new medical instruments for diagnosing and treating disease. These include MEMS optical scanner for endoscopic optical coherence tomographic imaging, micromirror devices for genetic microarray reading and tissue imaging, robotics for micromanipulations of MEMS components, carbon nanotube-based sensors for biomedical applications, and lab-on-a-chip designs.\rAdditionally, Professor Yeow’s company ARTsensing Inc. has commercialized an invention which is a product of his research – the world’s first transparent and flexible radiation detector that measures ionizing radiation delivered to cancer patients during treatment.  \rIn addition to his many accomplishments, Professor Yeow was the recipient of the Young Engineer Award from the Ontario Society of Professional Engineers in 2008.'},
 {'name': 'John Zelek',
  'job_title': 'Associate Professor & Co-Director VIP (Vision Image Processing) Lab',
  'email': 'jzelek@uwaterloo.ca',
  'phone': ' 519-888-4567 x32567',
  'location': ' EC4 2017',
  'profile_image': 'https://ofis.uwaterloo.ca/profile/jzelek.png',
  'research_interests': ['Wearable Sensory Substitution',
   ' Computer Vision',
   ' Haptics',
   ' Robotics',
   ' Wayfinding',
   ' Ergonomics',
   ' Human Factors & Biomedical',
   ' Modeling & Simulation',
   ' Signal & Image Processing',
   ' Intelligent Mechatronic Control Systems',
   ' Vibrotactile Stimulation',
   ' Dynamic Probabilistic Computer Vision Techniques',
   ' Mobile Robot Navigation',
   ' Human-robot Interaction',
   ' Automotive',
   ' Connectivity And Internet Of Things',
   ' Operational Artificial Intelligence',
   ' IoT',
   ' Devices'],
  'biography': 'Professor Zelek is an Associate Professor and co-director of the VIP (Vision Image Processing) lab.  He is formerly the Associate Graduate Chair of Systems Design Engineering, serving from 2013 to 2017.\rProfessor Zelek’s current main research interests include autonomous robotic mapping and localization,  3D scene understanding, man made infrastructure assessment (e.g., roads, buildings, bridges), eye (fundus, OCT) image understanding for disease,  learning 3D models from single-views, athletic sport tracking & biomechanical understanding of play & ability from video feeds, to name a few.  Some of these projects make use of AI & deep learning techniques.\rProf. Zelek’s interests in the past have included assistive devices, social engineering, haptics, robot navigation to name a few.\r Professor Zelek has been the co-founder of two startup companies: Tactile Sight and Sweep3D.  Tactile Sight commercialized a haptic navigation device for people who are cognitively (e.g., dementia) or perceptually (e.g., blind) disabled.  Sweep3D commercialized technology that produces 3D models by sweeping a camera around objects or spaces for various applications including clothes fitting, orthotics as well as  well as exploring real estate premises remotely.  Professor Zelek also sits on the advisory boards for Intelligent Health Solutions Inc. and EyeCheck.'}]
module.exports = db